Adding spack recipe for hipsparse
ROCm/rocm-spack-pkgs pull request #12
Opened 2020-07-22 05:23 UTC by arjun-raj-kuppala

2020-07-22 17:05 UTC, srekolam commented on packages/hipsparse/package.py
> +    """hipSPARSE is a SPARSE marshalling library, with multiple supported backends. It sits between the application and a
the line colums allowed is 79..any thing more i see flake8 errors.Also ensure no trailing whitespaces..

2020-07-22 17:09 UTC, srekolam commented on packages/hipsparse/package.py
> +               '-DCMAKE_CXX_FLAGS=-I {0}/include'.format(self.spec['hsa-rocr-dev'].prefix),
i think the allowed width is 79. so, split the line. also.. With the args [ ] , i see some issues with indentation which is leading to flake8 errors after we push to spack

2020-07-22 17:10 UTC, srekolam requested changes
please address the cosmetic errors otherwise will give flake8 issues later on.. i have still bunch of them open

2020-07-24 01:31 UTC, arjun-raj-kuppala reviewed
@srekolam All the flake8 issues are addressed, please review and merge this

2020-07-24 16:39 UTC, srekolam approved these changes

2020-07-24 17:18 UTC, merged