Added AOMP Spack recipe.
ROCm/rocm-spack-pkgs pull request #16
Opened 2020-08-05 19:36 UTC by estewart08

There are currently three missing tags for hip, vdi, and opencl. Once created
the package will need updated with the checksums.

For now the spack install will have to include '--no-checksum':
spack install --no-checksum aomp

Still making a package dependency list to see if Spack needs to support additional distribution packages for various operating systems.

2020-08-06 04:33 UTC, arjun-raj-kuppala commented
I am currently validating this recipe in my environment, will confirm post completion.

2020-08-06 04:47 UTC, arjun-raj-kuppala commented on packages/aomp/package.py
> +                                          '-DCMAKE_C_COMPILER=/usr/bin/gcc-7',
We shouldn't be setting c and c++ compiler explicitly, spack take care of that.

2020-08-07 19:19 UTC, arjun-raj-kuppala requested changes
As discussed, pls incorporate gcc/ar from spack and also build was broken with centos os, request you to make the appropriate changes.

2020-08-07 19:19 UTC, arjun-raj-kuppala commented on packages/aomp/package.py
> +                                          '-DCMAKE_AR=/usr/bin/ar'
This needs to be declared as spack dependency and used here. Basically avoid system binaries/tools as much as possible....

2020-08-11 00:05 UTC, estewart08 commented on packages/aomp/package.py
> +                                          '-DCMAKE_AR=/usr/bin/ar'
Centos should build now, added binutils as a dependency.

2020-08-11 00:05 UTC, estewart08 commented on packages/aomp/package.py
> +                                          '-DCMAKE_C_COMPILER=/usr/bin/gcc-7',
Done.

2020-08-11 04:11 UTC, merged